### ISSUE TITLE
Writing use case scenarios

### ISSUE THREAD

**Issue by korayozgurbuz** [swe-ms-boun/2018fall-swe574-g3#16]

**Comment by nihaler** [comment]
https://github.com/swe-ms-boun/2018fall-swe574-g3/wiki/4.1-Agile-User-Stories-&-Use-Case-Scenarios

Under this link, use case scenarios has been completed, please also check @korayozgurbuz @firatt @ahmetanilgur @yankiinsel , then we can close this issue.
