### ISSUE TITLE
Trial date expiration in Balsamiq

### ISSUE THREAD

**Issue by korayozgurbuz** [swe-ms-boun/2018fall-swe574-g3#19]
A UML Class diagram will be drawn which shows the system's classes, their attributes, methods and the relationships among objects.

**Comment by ahmetanilgur** [comment]
trying out edraw right now

**Comment by firatt** [comment]
i found this useful: http://dia-installer.de/

**Comment by ahmetanilgur** [comment]
edraw is compatible on all 3 operating systems and free, we should give it try imo.
been using on mac, works flawlessly
