### ISSUE TITLE
Create UML diagrams for posting

### ISSUE THREAD

**Issue by korayozgurbuz** [swe-ms-boun/2018fall-swe574-g3#20]
- [x] Class Diagram
- [x] Sequence Diagram

**Comment by firatt** [comment]
I've created class and sequence diagrams, needs revision thou.

**Comment by firatt** [comment]
i've created class and sequence diagrams for posting but PostControllerClass is missing on class diagrams but it appears on sequence diagrams. i'll fix that soon.
