### ISSUE TITLE
facebooka authorization sayfasında login olamama

### ISSUE THREAD

**Issue by korayozgurbuz** [swe-ms-boun/2018fall-swe574-g3#55]
biz developer.facebook.com'dan kullanıcıyı test kullanıcısı yapmadığımız sürece kullanıcı authorization sayfasında login olamıyor, error alıyor: [Görsel](https://i.postimg.cc/HTQ2f0xp/login-Error.png)

**Comment by ahmetanilgur** [comment]
bug değil feature :small_blue_diamond: 
olması gereken zaten bu. bug tagini kaldırıyorum.
